### PR TITLE
Added footer with the required social media handles.

### PR DESCRIPTION
**Pull request by mb-008**
As per the required details.I have added the footer with social media logo and their respective links to this web app.

### CODE REVIEW

**Review by Arman-ali-khan-786 — COMMENTED** [review]
hey you have created a seperate folder replicated the old files and made the changes , this will not be entertained ..

**Comment by Arman-ali-khan-786** [comment]
and dont make unnecessary changes ok

**Comment by mb-008** [comment]
@Arman-ali-khan-786 sir, why did u add the spam label ? i have just tried to make a footer in your web application with social media icons and links and their icons.I am just a newbie in the field of open-Source and instead of helping me with the exact requirements that u wanted in your issue. you just added the spam and invalid label.If u don't want to merge this pr then it's okay but please remove the label and i will delete your forked repo and take back my pr

**Comment by mb-008** [comment]
@Arman-ali-khan-786 please reply to my query?

**Pull request closed without merging**
